name: Deploy Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Npm Install
        env:
          CI: true
        run: |
          npm ci
      - name: Npm Build
        run: |
          npm run build
      - name: Zip File
        run: |
          zip -j deploy.zip ./built/*
      - name: Deploy
        run: |
          aws lambda update-function-code --function-name=budget-loader --zip-file=fileb://deploy.zip
